### ISSUE TITLE
Rebalancer is getting stuck with 'RPC services not available' error

### ISSUE THREAD

**Issue by itsneski** [itsneski/lightning-jet#13]
Error: Error: 2 UNKNOWN: waiting to start, RPC services not available from /tmp/autorebalance.log.

The service is running based on jet status, but rebalances arent being kicked off.

Noticed during alpha testing (at least two instances).

workaround: `jet restart rebalancer`

**Comment by itsneski** [comment]
workaround: `jet restart rebalancer`

**Comment by itsneski** [comment]
fixed by adding try & catch around classify.

**Comment by itsneski** [comment]
The issue keeps on re-occurring. The rebalancer is getting stuck with 'Error: Error: 2 UNKNOWN: waiting to start, RPC services not available'.  Debugging the issue. Added extra notifications in the jet monitor and the telegram bot.

**Comment by itsneski** [comment]
The same issue occurred in the telegram bot service. It looks like lnd grpc connect is getting dropped (intermittently), which causes jet services to stall.

/home/umbrel/mytools/lnd-api/utils.js:457
      if (err) throw new Error(err);
               ^

Error: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callback (/home/umbrel/mytools/lnd-api/utils.js:457:22)
    at Object.onReceiveStatus (/home/umbrel/mytools/node_modules/@grpc/grpc-js/build/src/client.js:179:36)
    at Object.onReceiveStatus (/home/umbrel/mytools/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/home/umbrel/mytools/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /home/umbrel/mytools/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processTimers (internal/timers.js:494:9)
    at Function.module.exports.runLoopOnce (/home/umbrel/mytools/node_modules/deasync/index.js:65:10)
    at fetchTelegramMessageSync (/home/umbrel/mytools/db/utils.js:61:28)
    at Timeout.pollMessages [as _onTimeout] (/home/umbrel/mytools/service/telegram.js:78:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    at Function.module.exports.runLoopOnce (/home/umbrel/mytools/node_modules/deasync/index.js:65:10)
    at Object.getInfoSync (/home/umbrel/mytools/lnd-api/utils.js:461:26)
    at Object.listFees (/home/umbrel/mytools/lnd-api/utils.js:284:31)
    at listFeesSync (/home/umbrel/mytools/lnd-api/utils.js:272:20)
    at Timeout.monitorFees [as _onTimeout] (/home/umbrel/mytools/service/telegram.js:28:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by itsneski** [comment]
Identified an issue within the layer that communicates with lnd.  One grpc handle is being reused for multiple grpc calls.  A new handle needs to be generated upon connection reset.
