### ISSUE TITLE
Monitor Errors Out on Unknown Node

### ISSUE THREAD

**Issue by NanIthilHODL** [itsneski/lightning-jet#30]
A node opened a channel to me, but it seems like their node is new and not known to the network.  Jet monitor exited with an error.  It seems that I won't be able to use monitor until this node is known.

```
node: 021358c92d60fa9fc4abbdd0645de3ee581d27ee9366d897317aa344a8f3768b26, error: Error: 5 NOT_FOUND: unable to find node
(node:18087) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of null
    at /home/bos/lightning-jet/api/utils.js:163:20
    at Array.forEach (<anonymous>)
    at listForcedClosingFormattedSync (/home/bos/lightning-jet/api/utils.js:162:17)
    at runMonitorLoop (/home/bos/lightning-jet/jet:377:16)
    at /home/bos/lightning-jet/jet:315:7
    at new Promise (<anonymous>)
    at Command._action (/home/bos/lightning-jet/jet:313:12)
    at Command._run (/home/bos/lightning-jet/node_modules/caporal/lib/command.js:483:42)
    at Program._run (/home/bos/lightning-jet/node_modules/caporal/lib/program.js:183:16)
    at Program.parse (/home/bos/lightning-jet/node_modules/caporal/lib/program.js:289:17)
    at Object.<anonymous> (/home/bos/lightning-jet/jet:342:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18087) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by NanIthilHODL** [comment]
Error was while the channel was in a pending open state.  After successful open no error was received.

**Comment by itsneski** [comment]
Will beef up null checks. The change will be part of the next git push.
