### ISSUE TITLE
jet logger (htlc-logger) service does not recover after an exception

### ISSUE THREAD

**Issue by itsneski** [itsneski/lightning-jet#33]
The exception occurred due to the lnd API connection being terminated by lnd.  The exact root cause for why the connection is terminated is unknown, but it is likely due to lnd being overloaded.

When an exception occurs, it causes the stream of htlc events to terminate, subsequently resulting in missed hltcs not being recorded in the database.

logging events...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: 2 UNKNOWN: htlc event subscription terminated
    at Object.callErrorFromStatus (/home/jeremy/lightning-jet/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/jeremy/lightning-jet/node_modules/@grpc/grpc-js/build/src/client.js:330:49)
    at Object.onReceiveStatus (/home/jeremy/lightning-jet/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /home/jeremy/lightning-jet/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 2,
  details: 'htlc event subscription terminated',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by itsneski** [comment]
Fixed by adding error handling and the logger server restart in the daddy service.
