### ISSUE TITLE
htlc analyzer crashes when there are no htlcs

### ISSUE THREAD

**Issue by Cameri** [itsneski/lightning-jet#43]
Log:
```
[cameri@umbrel lightning-jet-config]$ sudo docker exec -it lightning-jet cat /tmp/autorebalance.log
max commands: 10
max ppm: 500
max pending htlcs: 4
classifying peers...
no events found
classify: TypeError: Cannot read properties of undefined (reading 'peers')
    at classifyPeersAnalyzer (/app/api/htlc-analyzer.js:20:16)
    at classify (/app/service/autorebalance.js:125:18)
    at Object.<anonymous> (/app/service/autorebalance.js:100:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
finished classifying
12/31 05:16 AM
generating htlc history...

--------------------------------
12/31 05:16 AM
runLoop error: TypeError: Cannot read properties of undefined (reading 'inbound')
TypeError: Cannot read properties of undefined (reading 'inbound')
    at runLoopExec (/app/service/autorebalance.js:157:14)
    at runLoop (/app/service/autorebalance.js:139:5)
    at Object.<anonymous> (/app/service/autorebalance.js:106:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by itsneski** [comment]
Fix is on the dev branch. Will be pushed in the next release. Affects users that have zero missed htlcs over the 24h period.

**Comment by itsneski** [comment]
Performed selective merge into the main branch. This issue is important enough to get merged early without waiting for the next release.
