### ISSUE TITLE
Rebalancer Error (Raspiblitz)

### ISSUE THREAD

**Issue by NanIthilHODL** [itsneski/lightning-jet#54]
After running 1.3.0 rebalancer gets "stuck."  I.e., jet monitor thinks rebalances are in process and in fact associated processes are running, but no htlcs appear, rebalances never countdown, etc.

Runining on Raspiblitz 1.7.1, lightning-jet installed under the "bos" user.

Example error from rebalance log follows:
```
* rebalancing from BCash_Is_Trash to SeasickDiver
* remaining amount: 1,000,000
* time left: 30 mins
(node:9153) UnhandledPromiseRejectionWarning: Error: Cannot find module 'balanceofsatoshis/lnd'
Require stack:
- /home/bos/lightning-jet/bos/rebalance.js
- /home/bos/lightning-jet/api/rebalance.js
- /home/bos/lightning-jet/jet
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at lazy (/home/bos/lightning-jet/node_modules/import-lazy/index.js:3:33)
    at Object.get (/home/bos/lightning-jet/node_modules/import-lazy/index.js:11:22)
    at lndForNode (/home/bos/lightning-jet/bos/rebalance.js:5:42)
    at Object.rebalance (/home/bos/lightning-jet/bos/rebalance.js:67:29)
    at rebalanceSync (/home/bos/lightning-jet/bos/rebalance.js:23:20)
    at module.exports (/home/bos/lightning-jet/api/rebalance.js:232:20)
    at Object.apply (/home/bos/lightning-jet/node_modules/import-lazy/index.js:16:20)
    at /home/bos/lightning-jet/jet:95:7
    at new Promise (<anonymous>)
    at Command._action (/home/bos/lightning-jet/jet:92:12)
    at Command._run (/home/bos/lightning-jet/node_modules/caporal/lib/command.js:483:42)
    at Program._run (/home/bos/lightning-jet/node_modules/caporal/lib/program.js:183:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by itsneski** [comment]
did you run npm install?

**Comment by NanIthilHODL** [comment]
No, my mistake!
