### ISSUE TITLE
Rebalancer restarting!

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#56]
The rebalancer restarted out of the blue this morning and the telegram bot reported nicely :-)

<img width="187" alt="image" src="https://user-images.githubusercontent.com/33904339/149892867-811b875a-0f1b-4b23-b602-312fc15c6e69.png">

![telegram-cloud-photo-size-4-5994318399003539078-y](https://user-images.githubusercontent.com/33904339/149892693-cbb206e5-a486-4e5f-8b16-08b9ec3282b3.jpg)

The following entry was found in /tmp/autorebalancer.log:

```
runLoop error: TypeError: Cannot read properties of null (reading 'fee_base_msat')                                                          
TypeError: Cannot read properties of null (reading 'fee_base_msat')
    at /home/umbrel/lightning-jet/lnd-api/utils.js:241:43
    at Array.forEach (<anonymous>)
    at /home/umbrel/lightning-jet/lnd-api/utils.js:220:15
    at end (/home/umbrel/lightning-jet/node_modules/run-parallel/index.js:21:15)                                                            
    at done (/home/umbrel/lightning-jet/node_modules/run-parallel/index.js:25:10)                                                           
    at each (/home/umbrel/lightning-jet/node_modules/run-parallel/index.js:31:7)                                                            
    at /home/umbrel/lightning-jet/node_modules/run-parallel/index.js:46:37                                                                  
    at Object.callback (/home/umbrel/lightning-jet/lnd-api/utils.js:208:18)                                                                 
    at Object.onReceiveStatus (/home/umbrel/lightning-jet/node_modules/@grpc/grpc-js/build/src/client.js:177:36)                            
    at Object.onReceiveStatus (/home/umbrel/lightning-jet/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)              
Error: async hook stack has become corrupted (actual: 540059, expected: 4110)                                                               
 1: 0xa536f4 node::AsyncWrap::PopAsyncContext(v8::FunctionCallbackInfo<v8::Value> const&) [node]                                            
 2: 0xd2b230  [node]
 3: 0xd2c28c v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]                                        
 4: 0x154a28c  [node]
```

Maybe the cause is a new channel opening, as at around the same time a new incoming channel has been opened :-)

**Comment by itsneski** [comment]
Good thing that jet is resilient to failures and was able to recover. At the same time, it should handle exceptions gracefully.  In this particular case, it is likely that a new channel was added, but the fee info was not yet available, hence the null pointer exception when trying to access the fee policy field.

Will be addressed in the next git push.
