### ISSUE TITLE
jet analyze-fees crashed on a channel with incomplete data

### ISSUE THREAD

**Issue by stonedbear** [itsneski/lightning-jet#84]
Something went wrong with a channel that i was trying to open, it caused jet analyze-fees crash with the following error:

```
home/admin/lightning-jet/jet:244
        let num = printFeeAnalysis(c.name, c.peer, feeMap[c.peer].local, feeMap[c.peer].remote, options.profit);
                                                                  ^

TypeError: Cannot read properties of undefined (reading 'local')
    at /home/admin/lightning-jet/jet:244:67
    at Array.forEach (<anonymous>)
    at /home/admin/lightning-jet/jet:242:27
    at new Promise (<anonymous>)
    at Command._action (/home/admin/lightning-jet/jet:171:12)
    at Command._run (/home/admin/lightning-jet/node_modules/caporal/lib/command.js:483:42)
    at Program._run (/home/admin/lightning-jet/node_modules/caporal/lib/program.js:183:16)
    at Program.parse (/home/admin/lightning-jet/node_modules/caporal/lib/program.js:289:17)
    at Object.<anonymous> (/home/admin/lightning-jet/jet:614:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```
What solved it for me was to force close that channel.

**Comment by itsneski** [comment]
This will be addressed in the upcoming jet release 🚀 ⚡  Doing extra testing for a variety of scenarios on the test node.
